image:
  repository: tccr.io/truecharts/sshwifty
  pullPolicy: IfNotPresent
  tag: latest@sha256:3f4f3c44825a1bf3b1320194077b9e1fda44b5ad30f9070c4db2a638512bbf10

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/"
            readiness:
              path: "/"
            startup:
              path: "/"
          env:
            # empty to accept request from all hosts
            SSHWIFTY_HOSTNAME: ""
            # web access password
            SSHWIFTY_SHAREDKEY: ""
            DialTimeout: 10
            # SSHWIFTY_SOCKS5: "" When set, Sshwifty backend will try to connect remote through the given proxy
            # SSHWIFTY_SOCKS5_USER
            # SSHWIFTY_SOCKS5_PASSWORD
            SSHWIFTY_LISTENPORT: "{{ .Values.service.main.ports.main.port }}"
            SSHWIFTY_LISTENINTERFACE: "0.0.0.0"
            SSHWIFTY_INITIALTIMEOUT: 3
            SSHWIFTY_READTIMEOUT: 60
            SSHWIFTY_WRITETIMEOUT: 60
            SSHWIFTY_HEARTBEATTIMEOUT: 20
            SSHWIFTY_READDELAY: 10
            SSHWIFTY_WRITEELAY: 10
            # SSHWIFTY_TLSCERTIFICATEFILE: ""
            # SSHWIFTY_TLSCERTIFICATEKEYFILE: ""
            # SSHWIFTY_PRESETS: [] json obj array https://github.com/nirui/sshwifty#configuration-file | preset section.
            SSHWIFTY_ONLYALLOWPRESETREMOTES: false

service:
  main:
    ports:
      main:
        protocol: http
        port: 8182

portal:
  open:
    enabled: true
