image:
  repository: tccr.io/truecharts/octoprint
  tag: 1.8.7@sha256:fb8ad50f23c243072320b40cfb41cbaf83e91128f2ff1ee03f9b518b9d1c5a93
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10021
        targetPort: 80
persistence:
  data:
    enabled: true
    mountPath: "/octoprint"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            ENABLE_MJPG_STREAMER: "true"
            # -- sets the Mjpg stream imput parameters
            # Example "-y -n -r 640x480"
            MJPG_STREAMER_INPUT:
            # -- sets the camera dev parameters
            # Example "/dev/video0"
            CAMERA_DEV:
