image:
  repository: tccr.io/truecharts/esphome
  pullPolicy: IfNotPresent
  tag: 2023.4.2@sha256:61570fcb6e6f573cc04b375bc89ef5dad93f68ad3ed25ebb89ccc751448bb4ed

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    privileged: true
    allowPrivilegeEscalation: true
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 6052
        targetPort: 6052

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env:
            ESPHOME_DASHBOARD_USE_PING: false
            ESPHOME_DASHBOARD_RELATIVE_URL: /
            # ESPHOME_QUICKWIZARD:
            # ESPHOME_IS_HASSIO:
            # DISABLE_HA_AUTHENTICATION:
            # USERNAME:
            # PASSWORD:

persistence:
  config:
    enabled: true
    mountPath: /config
  platformio:
    enabled: true
    mountPath: /.platformio
portal:
  open:
    enabled: true
