image:
  repository: tccr.io/truecharts/zwavejs-ui
  pullPolicy: IfNotPresent
  tag: 8.14.2@sha256:bed3e9a090a0bbb8d35e01c27f8ac4b6cd4152dcd738923ee32005d02d17687f
service:
  main:
    ports:
      main:
        port: 8091
        targetPort: 8091
  ws:
    enabled: true
    ports:
      ws:
        enabled: true
        port: 10046
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: "/usr/src/app/store"
# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: app
#           operator: In
#           values:
#           - zwave-controller

portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: true
              # custom: true
              # spec:
              #   failureThreshold: 5
              #   httpGet:
              #     path: /health
              #     port: http
              #     httpHeaders:
              #       - name: Accept
              #         value: text/plain
              #   initialDelaySeconds: 30
              #   periodSeconds: 10
              #   timeoutSeconds: 10
            readiness:
              enabled: true
              # custom: true
              # spec:
              #   failureThreshold: 5
              #   httpGet:
              #     path: /health
              #     port: http
              #     httpHeaders:
              #       - name: Accept
              #         value: text/plain
              #   initialDelaySeconds: 30
              #   periodSeconds: 10
              #   timeoutSeconds: 10
            startup:
              enabled: false
              # custom: true
              # spec:
              #   failureThreshold: 5
              #   httpGet:
              #     path: /health
              #     port: http
              #     httpHeaders:
              #       - name: Accept
              #         value: text/plain
              #   initialDelaySeconds: 30
              #   periodSeconds: 10
              #   timeoutSeconds: 10
