image:
  repository: tccr.io/truecharts/syslog-ng
  pullPolicy: IfNotPresent
  tag: 4.1.1@sha256:89852985cb5a7eefa5481c79a92c120b428f0426fbbc8aee918bbd5d8ffba302
service:
  main:
    ports:
      main:
        targetPort: 601
        port: 6601
  syslog-udp:
    enabled: true
    ports:
      syslog-udp:
        enabled: true
        protocol: udp
        targetPort: 514
        port: 5514
  syslog-tls:
    enabled: true
    ports:
      syslog-tls:
        enabled: true
        targetPort: 6514
        port: 6514
persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: false
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
