image:
  repository: tccr.io/truecharts/cyberchef
  tag: 10.4.0@sha256:c94911b26c44ae76c76c288b2536a336ddacccc3b87ba7180655fb8bcd9d702b
  pullPolicy: IfNotPresent

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 10219
        protocol: http
        targetPort: 8000

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /
            readiness:
              type: http
              path: /
            startup:
              type: http
              path: /
          env: {}

portal:
  open:
    enabled: true
