image:
  repository: tccr.io/truecharts/domoticz
  pullPolicy: IfNotPresent
  tag: 2023.1.20230427@sha256:526cbc2f76de65c9d27e426f2557e12ccc9a78fab7bd7a241a525da79e8f2efe

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 10144
  comm1:
    enabled: true
    ports:
      comm1:
        enabled: true
        targetPort: 6144
        port: 6144
  comm2:
    enabled: true
    ports:
      comm2:
        enabled: true
        targetPort: 1443
        port: 1443

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
          env:
            WEBROOT: "domoticz"

persistence:
  config:
    enabled: true
    mountPath: /config

portal:
  open:
    enabled: true
