image:
  repository: tccr.io/truecharts/tinymediamanager
  tag: 4.3.10@sha256:cd74d01de27be1edfad026fc45fab7a8dc00bf56f32809f4131af448f94e27d1
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10179
        targetPort: 4000
persistence:
  data:
    enabled: true
    mountPath: "/data"
  movies:
    enabled: true
    mountPath: "/media/movies"
  tvshows:
    enabled: true
    mountPath: "/media/tvshows"
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PASSWORD: ""
