image:
  repository: tccr.io/truecharts/homepage
  tag: 0.6.16@sha256:fdd59256c7cdc79dbda1d7b6a7f13c9bd8ae1de0f89eaaf8481f633419a44049
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10352
        protocol: http
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: /app/config
portal:
  open:
    enabled: true
