image:
  repository: tccr.io/truecharts/openspeedtest
  pullPolicy: IfNotPresent
  tag: latest@sha256:e1632993ff1c01ae85cf002ff32259d8784cacc122f72e56a6bde24c236227c3
service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 3000
        port: 10256
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
