image:
  repository: tccr.io/truecharts/pwndrop
  pullPolicy: IfNotPresent
  tag: v1.0.1@sha256:40cf6c2996fea33016b82700da8796a4a1a0d767997410da0e87b3a2930075e0
service:
  main:
    ports:
      main:
        targetPort: 8080
        port: 10149
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
