image:
  repository: tccr.io/truecharts/flaresolverr
  pullPolicy: IfNotPresent
  tag: 3.1.2@sha256:768d9c5b20c2cedc0e568ebb96d5202debd247651311acc7a78ee224c70c3ab6

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        port: 8191
        targetPort: 8191

persistence:
  config:
    enabled: true
    mountPath: /config

portal:
  open:
    enabled: true
