image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/rdesktop
  tag: latest@sha256:b997016b6e92278485f0806e8213114f7586a25e46d4c9173aed36fc05a039d2
ubuntuXFCEImage:
  repository: tccr.io/truecharts/rdesktop-ubuntu-xfce
  tag: latest@sha256:61ff64ba43dd1b244e0334555750cc783beb46cdd9885f98af7f324baee08237
  pullPolicy: Always
fedoraXFCEImage:
  repository: tccr.io/truecharts/rdesktop-fedora-xfce
  tag: latest@sha256:748d26a1f2553dd4d71460581b2499aa5a163eea084228a3dc180533b58b19af
  pullPolicy: Always
archXFCEImage:
  repository: tccr.io/truecharts/rdesktop-arch-xfce
  tag: latest@sha256:46b0e0076b49096ea8814419aca42b31e6e9426373d48d40803a86140c622808
  pullPolicy: Always
alpineKDEImage:
  repository: tccr.io/truecharts/rdesktop-alpine-kde
  tag: latest@sha256:56a8700dddfe676c64ff95559d0a3e530b894e093db3d08c2a8422de84575dbb
  pullPolicy: Always
ubuntuKDEImage:
  repository: tccr.io/truecharts/rdesktop-ubuntu-kde
  tag: latest@sha256:d9c2442bc04f77692477345aa9444b4208c482852a8ff2365f8ab3c99adfb7f2
  pullPolicy: Always
fedoraKDEImage:
  repository: tccr.io/truecharts/rdesktop-fedora-kde
  tag: latest@sha256:7ee78e5924534417e5ea8acfb6a381f769716ec05c439d5e8876c3df40d28de3
  pullPolicy: Always
archKDEImage:
  repository: tccr.io/truecharts/rdesktop-arch-kde
  tag: latest@sha256:f427c203c5adba9130777a53463786a1f7106cd4b7d205a7c6413ce223faa690
  pullPolicy: Always
alpineMATEImage:
  repository: tccr.io/truecharts/rdesktop-alpine-mate
  tag: latest@sha256:aece0e33c066fd45d4c1ab1ba4990aa04133f285bca170aa2a50b17bf9a8d9b2
  pullPolicy: Always
ubuntuMATEImage:
  repository: tccr.io/truecharts/rdesktop-ubuntu-mate
  tag: latest@sha256:012fba78ab5177db21c6d51ea41a665036d09b73afbfdc0a62484c4cd6001a7c
  pullPolicy: Always
fedoraMATEImage:
  repository: tccr.io/truecharts/rdesktop-fedora-mate
  tag: latest@sha256:ec3a5d020543523c8266d152300ffd7db8b95089ce53ef425fdd790a3d9e651c
  pullPolicy: Always
archMATEImage:
  repository: tccr.io/truecharts/rdesktop-arch-mate
  tag: latest@sha256:ab48d20196e1c594b895f971451f3dc5205ea0fbc6c0ee8ab549c7fe848383b6
  pullPolicy: Always
alpineI3Image:
  repository: tccr.io/truecharts/rdesktop-alpine-i3
  tag: latest@sha256:a6f507d7b1c777067490d301db104909e6a7bb622328a9a9af68360493e59225
  pullPolicy: Always
ubuntuI3Image:
  repository: tccr.io/truecharts/rdesktop-ubuntu-i3
  tag: latest@sha256:cd21f2600dff90a1faa9b3d27ad8ce17b41d89a7faac4cac0be73f97e333346e
  pullPolicy: Always
fedoraI3Image:
  repository: tccr.io/truecharts/rdesktop-fedora-i3
  tag: latest@sha256:c0224d490d2a2e3f37907a839b9d62ce764458f8198a27727619fcd684953d22
  pullPolicy: Always
archI3Image:
  repository: tccr.io/truecharts/rdesktop-arch-i3
  tag: latest@sha256:698a76f46b2380882c88688e525a7e7ca5043ad0ad6921456accfcef330f644b
  pullPolicy: Always
alpineOpenBoxImage:
  repository: tccr.io/truecharts/rdesktop-alpine-openbox
  tag: latest@sha256:041c88cdb9bd9b1bda0a85c61daddd6d7d42109ade64bdc35d0fd7ee15c76eb4
  pullPolicy: Always
ubuntuOpenBoxImage:
  repository: tccr.io/truecharts/rdesktop-ubuntu-openbox
  tag: latest@sha256:5c743193e52aecc6220dd79d73dcccdb47047d27c4ac949793f26a117e760f8e
  pullPolicy: Always
fedoraOpenBoxImage:
  repository: tccr.io/truecharts/rdesktop-fedora-openbox
  tag: latest@sha256:6fa5017f13a44198e2708ed12edd80ffc549861715a4e1f94b25d94aa60249d3
  pullPolicy: Always
archOpenBoxImage:
  repository: tccr.io/truecharts/rdesktop-arch-openbox
  tag: latest@sha256:db8b7cee5ded1dc03ffac68f21475b82650758f334937e3cdf83cc4030ef7fa5
  pullPolicy: Always
alpineICEWMImage:
  repository: tccr.io/truecharts/rdesktop-alpine-icewm
  tag: latest@sha256:6dfac9ef9a351bf17db0ff1d3dd82b7d0b63174f5e48985027b5283be2c4506c
  pullPolicy: Always
ubuntuICEWMImage:
  repository: tccr.io/truecharts/rdesktop-ubuntu-icewm
  tag: latest@sha256:ca91250c609475ceadba980e28d874977c8e03e667af640fac4866bab95580de
  pullPolicy: Always
fedoraICEWMImage:
  repository: tccr.io/truecharts/rdesktop-fedora-icewm
  tag: latest@sha256:37560d75107c75a2252ab44bc8d86a76953d4ccd104832c175a349f2d56336b3
  pullPolicy: Always
archICEWMImage:
  repository: tccr.io/truecharts/rdesktop-arch-icewm
  tag: latest@sha256:93801d7243513d7bdcda632de4772c6315b2cdf119bf3f00e5bb50cae5219180
  pullPolicy: Always
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
service:
  main:
    ports:
      main:
        port: 3389
        protocol: http
        targetPort: 3389
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
