image:
  repository: tccr.io/truecharts/homarr
  tag: 0.12.1@sha256:cab7596755118d30fed37c54553e4b51887e387d0e7b3bd4319b362c8e166476
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10245
        targetPort: 7575
persistence:
  config:
    enabled: true
    mountPath: "/app/data/configs"
  icons:
    enabled: true
    mountPath: "/app/public/icons"
portal:
  open:
    enabled: true
