image:
  repository: tccr.io/truecharts/sabnzbd
  pullPolicy: IfNotPresent
  tag: 4.0.0@sha256:9efc1a8d4a6ef73cb3e084107877256002c9e358871c8fb359092da559ad31aa
service:
  main:
    ports:
      main:
        port: 10097
        targetPort: 8080
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SABNZBD__HOST_WHITELIST_ENTRIES: ""
