image:
  repository: tccr.io/truecharts/sickgear
  pullPolicy: IfNotPresent
  tag: latest@sha256:700f390966cce5637b37122f366d38d76cad6da1b39850ecc450b9d73ed10847
service:
  main:
    ports:
      main:
        port: 10066
        targetPort: 8081
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            APP_DATA: /config
