image:
  repository: tccr.io/truecharts/autobrr
  pullPolicy: IfNotPresent
  tag: 1.24.1@sha256:98c98719eb1b008f2b6ab22db87a3e1222707908da97b2c9e10d76e2a6197b7d

service:
  main:
    ports:
      main:
        port: 7474
        protocol: http
        targetPort: 7474

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: true
              type: exec
              command:
                - /bin/sh
                - -c
                - curl --fail localhost:7474/
            readiness:
              enabled: true
              type: exec
              command:
                - /bin/sh
                - -c
                - curl --fail localhost:7474/
            startup:
              enabled: true
              type: exec
              command:
                - /bin/sh
                - -c
                - curl --fail localhost:7474/

persistence:
  config:
    enabled: true
    mountPath: /config

portal:
  open:
    enabled: true
