image:
  repository: tccr.io/truecharts/picoshare
  tag: 1.3.3@sha256:02c631095d89b33f669c70dd69e446e053ac70036f72d573adea0c1a99d96a81
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 10209
persistence:
  data:
    enabled: true
    mountPath: "/data"
portal:
  open:
    enabled: true

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PORT: "{{ .Values.service.main.ports.main.port }}"
            PS_SHARED_SECRET: "somesecretcode"
            LITESTREAM_BUCKET: ""
            LITESTREAM_ENDPOINT: ""
            LITESTREAM_ACCESS_KEY_ID: ""
            LITESTREAM_SECRET_ACCESS_KEY: ""
