image:
  repository: tccr.io/truecharts/tautulli
  pullPolicy: IfNotPresent
  tag: 2.12.3@sha256:3d185f03df2ff1bc3491bb4baf228b95c559d4f7b7a826cb37004488ce33cc67
service:
  main:
    ports:
      main:
        port: 8181
        targetPort: 8181
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
