image:
  repository: tccr.io/truecharts/dockerregistry
  pullPolicy: IfNotPresent
  tag: v2@sha256:30949e8125d6a582af9c1bd9f30c24f4d017e7ba21021bb7b9f7bce629c43a64
service:
  main:
    ports:
      main:
        port: 10096
        targetPort: 8080
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
