image:
  repository: tccr.io/truecharts/prowlarr
  tag: 1.3.1.2796@sha256:8f926c593de39437cfe959570f34a16cbe2181ce26978542c775cb7296e6bb95
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 9696
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PROWLARR__PORT: "{{ .Values.service.main.ports.main.port }}"
            PROWLARR__AUTHENTICATION_METHOD: ""
