image:
  repository: tccr.io/truecharts/airdcpp-webclient
  pullPolicy: IfNotPresent
  tag: 2.11.4@sha256:afdd4b9fcfd9ee3939fb41935f616f49697be1504ae334a8f26b4c8a13186fb8

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
              path: /
            readiness:
              type: tcp
              path: /
            startup:
              type: tcp
              path: /
          env: {}

service:
  main:
    ports:
      main:
        protocol: tcp
        port: 10155
        targetPort: 5600
  unencrypted-tcp:
    enabled: true
    ports:
      unencrypted-tcp:
        enabled: true
        protocol: tcp
        port: 21248
        targetPort: 21248
  encrypted-tcp:
    enabled: true
    ports:
      encrypted-tcp:
        enabled: true
        protocol: tcp
        port: 21249
        targetPort: 21249
  search-udp:
    enabled: true
    ports:
      search-udp:
        enabled: true
        protocol: udp
        port: 21248
        targetPort: 21248

persistence:
  config:
    enabled: true
    mountPath: /.airdcpp

portal:
  open:
    enabled: true
