image:
  repository: tccr.io/truecharts/openvscode-server
  pullPolicy: IfNotPresent
  tag: 1.77.3@sha256:baa85c27e64d8cbf10e6ebd6830606fbf019935f6b0a891a7318f734c3bd3d5b
# secretEnv:
#   CONNECTION_TOKEN: "somerandomstring"
#   CONNECTION_SECRET: ""
#   SUDO_PASSWORD: ""
service:
  main:
    ports:
      main:
        targetPort: 3000
        port: 10135
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
