image:
  repository: tccr.io/truecharts/qinglong
  pullPolicy: IfNotPresent
  tag: 2.15.12@sha256:5a741df123398794759de65fddc474b70b32d3e043373dcef14e3c1b7ed0b162
service:
  main:
    ports:
      main:
        targetPort: 5700
        port: 10176
persistence:
  data:
    enabled: true
    mountPath: "/ql/data"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
