image:
  repository: tccr.io/truecharts/znc
  pullPolicy: IfNotPresent
  tag: v1.8.2@sha256:18f1163329c66bc358078819c20ef63a260bccf3f3f00781cea24fff56f90fea
service:
  main:
    ports:
      main:
        targetPort: 6501
        port: 6501
persistence:
  varrun:
    enabled: true
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
