image:
  repository: tccr.io/truecharts/sabnzbd
  pullPolicy: IfNotPresent
  tag: 3.7.2@sha256:2c31d99009505cf398944f2429a8a3109c067ee9946c715db5ba5ac2074de1b9
service:
  main:
    ports:
      main:
        port: 10097
        targetPort: 8080
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            SABNZBD__HOST_WHITELIST_ENTRIES: ""
