image:
  repository: tccr.io/truecharts/thelounge
  pullPolicy: IfNotPresent
  tag: v4.3.1@sha256:2a429efab1f1fa2a63310356c81226b900834657a07b509e674d7cd37a3a41fb
service:
  main:
    ports:
      main:
        port: 10061
        targetPort: 9000
persistence:
  config:
    enabled: true
    mountPath: "/config"
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            THELOUNGE_HOME: "/config"
