image:
  pullPolicy: IfNotPresent
  repository: tccr.io/truecharts/webtop
  tag: latest@sha256:8fd107bd7dcd79d42d955bf00de0719a89fffe1df2889aa1624bc48026272586
ubuntuXFCEImage:
  repository: tccr.io/truecharts/webtop-ubuntu-xfce
  tag: latest@sha256:5166bc928cbba8d4f7c0a4822aadb4f84c8023899b5d632b43eb05f0c8f9e588
  pullPolicy: Always
fedoraXFCEImage:
  repository: tccr.io/truecharts/webtop-fedora-xfce
  tag: latest@sha256:14593342b56a4937fdeb979ba1fb76d5545d13d2e25bd6f9749a7b10609aa84d
  pullPolicy: Always
archXFCEImage:
  repository: tccr.io/truecharts/webtop-arch-xfce
  tag: latest@sha256:aab8d9d672f0b36ab8dfa7b27d260cb9113f604ab1bc68410ad09f9f83f7d5d6
  pullPolicy: Always
alpineKDEImage:
  repository: tccr.io/truecharts/webtop-alpine-kde
  tag: latest@sha256:bf56358e6b1b56266d01e49fbfcbe2110fdc86ec34fc33d315dd2d45e7133766
  pullPolicy: Always
ubuntuKDEImage:
  repository: tccr.io/truecharts/webtop-ubuntu-kde
  tag: latest@sha256:b0802b7509d380e2f22795bf7c14484880878051758fe9113f231e656ac4dfd1
  pullPolicy: Always
fedoraKDEImage:
  repository: tccr.io/truecharts/webtop-fedora-kde
  tag: latest@sha256:9b0cb381713cc2090a3519b88dd801e590d01d0807343242a4141f32124edbc9
  pullPolicy: Always
archKDEImage:
  repository: tccr.io/truecharts/webtop-arch-kde
  tag: latest@sha256:8238fb7f41c56e801b52f8eabf01852f6b6056e08c76dcd1467e4d7b1e7c544a
  pullPolicy: Always
alpineMATEImage:
  repository: tccr.io/truecharts/webtop-alpine-mate
  tag: latest@sha256:6f1789ea7cb67f732629e21a156a4bba4b364a9aa1803b8b0ec5cf038c017331
  pullPolicy: Always
ubuntuMATEImage:
  repository: tccr.io/truecharts/webtop-ubuntu-mate
  tag: latest@sha256:ea5a7e96fee56e0d7c31bad889ff9818de498a30720f35eb55c050ea13bf2650
  pullPolicy: Always
fedoraMATEImage:
  repository: tccr.io/truecharts/webtop-fedora-mate
  tag: latest@sha256:2314b95493a033ba32e1bd22087add60d063733cd2a8f539233bbc4d56a1aa70
  pullPolicy: Always
archMATEImage:
  repository: tccr.io/truecharts/webtop-arch-mate
  tag: latest@sha256:f371403b90d6c070ad0e03d8bfa99268c44ac818b708bb4a1f9be6275333cee0
  pullPolicy: Always
alpineI3Image:
  repository: tccr.io/truecharts/webtop-alpine-i3
  tag: latest@sha256:8d7c8e0b16078606ce58c61b8fc42a0d090b86d304eb5a6bebe5ce3acc054124
  pullPolicy: Always
ubuntuI3Image:
  repository: tccr.io/truecharts/webtop-ubuntu-i3
  tag: latest@sha256:d8a460b45e6afab1b3bfe9a14e491114c059a248de200d566237dc68ad1dbbb6
  pullPolicy: Always
fedoraI3Image:
  repository: tccr.io/truecharts/webtop-fedora-i3
  tag: latest@sha256:ff8caa6502444e46148ab7808f8a6671403add576484e1564820b03a4e233aad
  pullPolicy: Always
archI3Image:
  repository: tccr.io/truecharts/webtop-arch-i3
  tag: latest@sha256:3467244a366e6a241efd8d840a6dcce8d722e3bd2a705bb04cd91278fb3ac1c4
  pullPolicy: Always
alpineOpenBoxImage:
  repository: tccr.io/truecharts/webtop-alpine-openbox
  tag: latest@sha256:865a85d389255186fc5bd1047ea9741f6eeb3db934495a47c30fcd3ce00f5587
  pullPolicy: Always
ubuntuOpenBoxImage:
  repository: tccr.io/truecharts/webtop-ubuntu-openbox
  tag: latest@sha256:502db5f6d584a1f8602ce3feef94602bf109869e37095555ff9cab5dcaec7df1
  pullPolicy: Always
fedoraOpenBoxImage:
  repository: tccr.io/truecharts/webtop-fedora-openbox
  tag: latest@sha256:493cef7bd649d0f9dc3029b30a63dab32fec4deb6349da28b4abc56fab5c90b9
  pullPolicy: Always
archOpenBoxImage:
  repository: tccr.io/truecharts/webtop-arch-openbox
  tag: latest@sha256:07f7b37bfaec391cc9eb3dc38531438a32036d2d4c71dc1b70cec6adf8b1aa81
  pullPolicy: Always
alpineICEWMImage:
  repository: tccr.io/truecharts/webtop-alpine-icewm
  tag: latest@sha256:b25a151a0b1f4ae9f60175cb1a7eab0469b3584f265f11242637b2c2e76f8a08
  pullPolicy: Always
ubuntuICEWMImage:
  repository: tccr.io/truecharts/webtop-ubuntu-icewm
  tag: latest@sha256:fa592c15bad6bdb55bb38756551822549c6ab1be5858db052116ee82c057527d
  pullPolicy: Always
fedoraICEWMImage:
  repository: tccr.io/truecharts/webtop-fedora-icewm
  tag: latest@sha256:cc73820e954fde10874185d0e82f5e15b29e691396bc9ed8a41229032e6de456
  pullPolicy: Always
archICEWMImage:
  repository: tccr.io/truecharts/webtop-arch-icewm
  tag: latest@sha256:cc8f014814a7f42d0b759db858632bb08c7fcec7b081c2faeca44f7aece56c08
  pullPolicy: Always
service:
  main:
    ports:
      main:
        port: 33000
        protocol: http
persistence:
  config:
    enabled: true
    mountPath: /config
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: image
          env:
            KEYBOARD: "en-us-qwerty"
            CUSTOM_PORT: "{{ .Values.service.main.ports.main.port }}"
