image:
  repository: tccr.io/truecharts/mylar3
  tag: 0.7.1@sha256:e39cca30962ebeef8ee6a99a6ff467bf1fdf7e66b16621271c4105dde9763d88
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 8090
        targetPort: 8090
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
