image:
  repository: tccr.io/truecharts/mstream
  pullPolicy: IfNotPresent
  tag: v5.11.4@sha256:951660eb389b9acb7d59dcb23175c4f293544ca3eccb2c6aae7c7bb665c21dfb
service:
  main:
    ports:
      main:
        port: 10041
        targetPort: 3000
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
