image:
  repository: tccr.io/truecharts/qbitmanage
  pullPolicy: IfNotPresent
  tag: 3.6.2@sha256:5f527d5aa6497a631ef05b4434276deb0c9fa46436e141c4d07b21226f347574
service:
  main:
    enabled: false
    ports:
      main:
        enabled: false
persistence:
  config:
    enabled: true
    mountPath: /config
  data:
    enabled: true
    mountPath: /data
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          env:
            QBT_RUN: false
            QBT_SCHEDULE: 30
            QBT_CROSS_SEED: false
            QBT_RECHECK: false
            QBT_CAT_UPDATE: false
            QBT_TAG_UPDATE: false
            QBT_REM_UNREGISTERED: false
            QBT_REM_ORPHANED: false
            QBT_TAG_NOHARDLINKS: false
            QBT_SKIP_RECYCLE: false
            QBT_DRY_RUN: false
            QBT_LOG_LEVEL: INFO
            QBT_DIVIDER: "="
            QBT_WIDTH: 100
