image:
  repository: tccr.io/truecharts/pgadmin4
  pullPolicy: IfNotPresent
  tag: v6.21.0@sha256:4062f40b48f3bc244bced54d2a85c43158760aef4736c3fa202f8298a4f3f35f
service:
  main:
    ports:
      main:
        port: 10024
        targetPort: 80
persistence:
  config:
    enabled: true
    mountPath: "/var/lib/pgadmin"
portal:
  open:
    enabled: true
securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0
    fsGroup: 5050
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            PGADMIN_DEFAULT_EMAIL: "replace@this.now"
            PGADMIN_DEFAULT_PASSWORD: "changeme"
