image:
  repository: tccr.io/truecharts/minio-console
  tag: 0.26.3@sha256:72ee6f126178bb954d28afd83553de8641a504f457f11bbeb92e6500955fddf9
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 9090
        targetPort: 9090
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            CONSOLE_MINIO_SERVER: ""
            CONSOLE_PBKDF_PASSPHRASE: "changeme"
            CONSOLE_PBKDF_SALT: "changeme"
          args: ["server"]
