image:
  repository: tccr.io/truecharts/homebox
  pullPolicy: IfNotPresent
  tag: 0.9.1@sha256:f404ce8478c07a1ba1c05cec53e5b11d4430178f56430435f67c983d5546a3b5
homebox:
  allow_registration: true
  auto_increment_asset_id: true
  max_upload_size: 10
  log_level: info
  log_format: text
  mailer_host: ""
  mailer_port: 587
  mailer_from: ""
  mailer_username: ""
  mailer_password: ""
service:
  main:
    ports:
      main:
        protocol: http
        port: 10603
persistence:
  data:
    enabled: true
    mountPath: /data
portal:
  open:
    enabled: true

workload:
  main:
    podSpec:
      containers:
        main:
          envFrom:
            - secretRef:
                name: "homebox-secret"
