image:
  repository: tccr.io/truecharts/mosdns
  pullPolicy: IfNotPresent
  tag: 5.1.3@sha256:0e524ab64b4e3d7f10a9c2c6907704c68a17467a38b0755a845c9786d73bdf1e
service:
  main:
    ports:
      main:
        targetPort: 53
        port: 53
      dns-upd:
        enabled: true
        protocol: udp
        targetPort: 53
        port: 53
persistence:
  data:
    enabled: true
    mountPath: "/etc/mosdns"
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
