image:
  repository: tccr.io/truecharts/soft-serve
  pullPolicy: IfNotPresent
  tag: 0.4.7@sha256:dd568932c6b3d5cf4b562eeebfc29bb870f77ce04c644b25cb6ad859b6184f57
softserve:
  host: localhost
  key_path: /.ssh/soft_serve_server_ed25519
  init_admin_key: ""
service:
  main:
    ports:
      main:
        protocol: tcp
        port: 23231
persistence:
  config:
    enabled: true
    mountPath: /soft-serve
  ssh:
    enabled: true
    mountPath: /.ssh
  repos:
    enabled: true
    mountPath: /repos
portal:
  open:
    enabled: false
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsGroup: 0
    runAsUser: 0
workload:
  main:
    podSpec:
      containers:
        main:
          envFrom:
            - secretRef:
                name: "env-secret"
