image:
  repository: tccr.io/truecharts/browserless-chrome
  tag: 1.58.0-chrome@sha256:e77842d0a1eb20e26b6a88b95902fcba370480d2b930401ddc93f68c8d67d418
  pullPolicy: IfNotPresent

puppeteerImage:
  repository: tccr.io/truecharts/browserless-chrome-puppeteer13
  pullPolicy: IfNotPresent
  tag: 1.58.0-puppeteer@sha256:c456f695ac3fb51c5ea37f76661b93ac960cce43c6ba3936d44711a4f733e6e0

service:
  main:
    ports:
      main:
        port: 10194
        protocol: http
        targetPort: 3000

workload:
  main:
    podSpec:
      containers:
        main:
          imageSelector: "image"
          probes:
            liveness:
              path: "/metrics"
            readiness:
              path: "/metrics"
            startup:
              path: "/metrics"
          env:
            WORKSPACE_DIR: "/downloads"
            METRICS_JSON_PATH: "/metrics/metrics.json"
            # User Defined

            HOST: ""
            WORKSPACE_DELETE_EXPIRED: false
            WORKSPACE_EXPIRE_DAYS: 30
            CHROME_REFRESH_TIME: 3600000
            MAX_CONCURRENT_SESSIONS: 5
            MAX_QUEUE_LENGTH: 5
            CONNECTION_TIMEOUT: 30000
            DEFAULT_BLOCK_ADS: true
            DEFAULT_HEADLESS: true
            DEFAULT_IGNORE_HTTPS_ERRORS: true
            DEFAULT_IGNORE_DEFAULT_ARGS: true
            ENABLE_API_GET: true
            FUNCTION_ENABLE_INCOGNITO_MODE: true
            EXIT_ON_HEALTH_FAILURE: true
            DISABLE_AUTO_SET_DOWNLOAD_BEHAVIOR: false
            ENABLE_DEBUGGER: true
            ENABLE_CORS: false
            ENABLE_XVBF: true
            # Enabling those, makes probe/app fail

            # KEEP_ALIVE: true

            # PREBOOT_CHROME: true
            TOKEN: ""

persistence:
  downloads:
    enabled: true
    mountPath: /downloads
  metrics:
    enabled: true
    mountPath: /metrics

portal:
  open:
    enabled: true
