image:
  repository: tccr.io/truecharts/medusa
  pullPolicy: IfNotPresent
  tag: 1.0.13@sha256:2e41757236372fdbc7ee175126c8b6cb31294611d56a425154754405cab61ba4
service:
  main:
    ports:
      main:
        port: 10068
        targetPort: 8081
persistence:
  config:
    enabled: true
    mountPath: "/config"
  varrun:
    enabled: true
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
